<?php
 include "header.php";
 ?>
<!-- About Secsion start -->
<section id="about" class="about">
	<h2>Tentang kami <span>IPA</span></h2>
	<div class="row">
		<div class="about-img">
			<img src="akhlak.jpg" width="500" height="500" alt="Tentang Kami">
		</div>
		<div class="content">
			<h3>AKH<span>LAK</span>.</h3>
			<P><span>Akhlak</span> adalah singkatan dari lima pilar pembangunan karakter kami yaitu: AMANAH <span>KOMPETEN </span>HARMONIS<span> LOYAL</span> ADAPTIF<span> KOLABORATIF</span>.</P>
			<p>Nilai-nilai perusahaan adalah identitas dan perekat budaya kerja yang mendukung peningkatan kinerja kami secara berkelanjutan.</P>
		</div>
	</div>
</section>
<!-- About Secsion start -->
 <?php
 include "footer.php";
 ?>


 <!-- product -->
 			<!-- BAJU MERAH PUTIH -->

			<div class="product-card">
				<div class="product-icons">
					<a href="#"><i data-feather="shopping-cart"></i></a>
					<a href="#" class="item-detail-button1"><i data-feather="eye"></i></a>
				</div>
				<div class="product-image">
					<img src="product 2.jpg" alt="product 2">
				</div>
				<div class="product-content">
					<h2>PAKET LENGKAP <br>
					SERAGAM MERAH PUTIH</h2>
					<div class="product-star">
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
					</div>
					<div class="product-price">IDR 233.000 /<span> IDR 380.000</span>
					</div>
				</div>
			</div>
		
		<!-- PULPEN -->

			<div class="product-card">
				<div class="product-icons">
					<a href="#"><i data-feather="shopping-cart"></i></a>
					<a href="#" class="item-detail-button1"><i data-feather="eye"></i></a>
				</div>
				<div class="product-image">
					<img src="product 3.jpg" alt="product 3">
				</div>
				<div class="product-content">
					<h2>PULPEN</h2>
					<div class="product-star">
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class=""></i>
					</div>
					<div class="product-price">IDR 2.500 /<span> IDR 2.800</span>
					</div>
				</div>
			</div>

			<!-- pensil -->

			<div class="product-card">
				<div class="product-icons">
					<a href="#"><i data-feather="shopping-cart"></i></a>
					<a href="#" class="item-detail-button1"><i data-feather="eye"></i></a>
				</div>
				<div class="product-image">
					<img src="product 4.jpg" alt="product 4">
				</div>
				<div class="product-content">
					<h2>PENSIL <br>
					tidak gampang patah</h2>
					<div class="product-star">
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class=""></i>
					</div>
					<div class="product-price">IDR 2.000 /<span> IDR 3.200</span>
					</div>
				</div>
			</div>

			<!-- simbol -->

			<div class="product-card">
				<div class="product-icons">
					<a href="#"><i data-feather="shopping-cart"></i></a>
					<a href="#" class="item-detail-button1"><i data-feather="eye"></i></a>
				</div>
				<div class="product-image">
					<img src="product 5.png" alt="product 5">
				</div>
				<div class="product-content">
					<h2>SIMBOL SEKOLAH<br>
					1 set </h2>
					<div class="product-star">
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class=""></i>
					</div>
					<div class="product-price">IDR 25.000<span> IDR 32.000</span>
					</div>
				</div>
			</div>




<div class="modal" id="item-detail-modal">
	<div class="modal-container">
		<a href="#" class="close-icon"><i data-feather="x-circle"></i></a>
		<div class="modal-content">
			<img src="product 1.jpg" alt="product 1">
			<div class="product-content">
				<h2>SERAGAM PUTIH HIJAU</h2>
				<p> seragam dengan kain berkualitas premium dari bahan kain katun, tidak mudah kuning dan sangat cocok untuk pemakaian 3 tahun, bahan elasatis karena terbuat dari benang woll, yang menambah ketahanan baju agar tidak mudah robek, bahan kualitas premium harga ekonomi menengah kebawah, buruan chaek out sebelum kehabisan.</p>
				<div class="product-star">
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class="rate"></i>
						<i data-feather="star" class=""></i>
						<i data-feather="star" class=""></i>
					</div>
					<div class="product-price">IDR 243.000 /<span> IDR 350.000</span></div>
					<a href="#"><i data-feather="shopping-cart"></i> <span>Tambah ke Keranjang</span></a>
			</div>
		</div>
	</div>
</div>